name: vidigi_package_dev
channels:
  - conda-forge
dependencies:
  - black
  - flake8
  - hatch
  - jupyterlab=4.2.4
  - jupyterlab-spellchecker=0.8.4
  - matplotlib=3.9.1
  - nbqa
  - numpy=1.26.2
  - pandas=2.0.1
  - pip=24.0
  - python=3.11
  - pytest=8.3.2
  - plotly=5.12.0
  - simpy=4.0.2
  - sim-tools=0.6.1
